[package]
name = "another-it-tg-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
reqwest = { version = "0.11", features = ["rustls-tls", "gzip", "brotli", "deflate"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"
html-escape = "0.2"
log = "0.4"
env_logger = "0.11"
