name: Notify

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - name: Run bridge
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: ./target/release/another-it-tg-bridge
